from .db.group import RPMTransaction
from .sack import Sack
from hawkey.package import Package

class Base:
    sack: Sack
    transaction: RPMTransaction

    def read_all_repos(self) -> None: ...
    def fill_sack(self) -> Sack: ...
    def install(self, pkg_spec: str) -> int: ...
    def upgrade_all(self) -> int: ...
    def resolve(self, allow_erasing: bool = ...) -> bool: ...
    def download_packages(self, pkglist: set[Package]) -> None: ...
    def do_transaction(self) -> int: ...
