name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.4", "3.12.0-beta.2"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install poetry
        run: pipx install poetry==1.5.1

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Use python ${{ matrix.python-version }} for poetry
        run: poetry env use ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit linters and checks
        run: poetry run pre-commit run --all-files
        if: ${{ matrix.python-version == '3.11.4' }}

      - name: Check typing with mypy
        run: poetry run mypy --strict

      - name: Run tests
        run: poetry run pytest tests
