name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install poetry
        run: pipx install poetry==1.3.1

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'
          cache: 'poetry'

      - name: Use python 3.11 for poetry
        run: poetry env use 3.11

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit linters and checks
        run: poetry run pre-commit run --all-files

      - name: Check typing with mypy
        run: poetry run mypy --strict

      - name: Run tests
        run: poetry run pytest tests
